### ISSUE TITLE
Calling I18n server side

### ISSUE THREAD

**Issue by kihira** [Ivorforce/YeGamolChattels#3]
Heyo,

In ItemEntityVita you use I18n in getItemStackDisplayName which causes a ClassNotFound exception server side. I recommend using the StatCollecter.translateToLocal instead as it's also server side :D

http://pastebin.com/0Y2pL8cJ

**Comment by Ivorforce** [comment]
Done, thanks for the report. 
Odd situation to find myself in, since I didn't think localized methods would never be called server-side, but at least it's a simple fix x)
