### ISSUE TITLE
Crash on chisel

### ISSUE THREAD

**Issue by kihira** [Ivorforce/YeGamolChattels#4]
A member managed to crash the server when trying to make a statue on my server.

Crash log: http://pastebin.com/5NS4ZLjk
Issue: Calling marked client only method quadCache on the server causes crash.

Using latest nightly build (at time of writing)
IvToolKit 1.0.2

**Comment by SpitefulFox** [comment]
Logging back in causes the server to instantly crash again as it tries to load the chunk with the statue.

**Comment by Ivorforce** [comment]
That was indeed very intelligent of me, thanks for reporting.
