### ISSUE TITLE
Client crash when breaking statues

### ISSUE THREAD

**Issue by ruyanve** [Ivorforce/YeGamolChattels#5]
Breaking a statue with a TiCon tool (not tested with vanilla since I am using Iguanas TiCon tweaks) crashes the client.
Server is fine.

Forge: 10.13.2.1291
YGC: YeGamolChattels-1.1.1.1.n35
IVToolkit: IvToolkit-1.0.4

detailed crashlog: http://pastebin.com/5rk3FkAG

**Comment by Ivorforce** [comment]
Thanks for reporting. The newest nightly should take care of this :)

**Comment by ruyanve** [comment]
Confirmed, thank you! :)
