### ISSUE TITLE
crash in modded server

### ISSUE THREAD

**Issue by myrmex1** [Ivorforce/YeGamolChattels#8]
I get this crash in my forge server I'm running on my local PC. It goes away if I uninstall Ivtoolkit and  YGC. https://gist.github.com/Qohelethh/0778f6de115231802753

**Comment by Ivorforce** [comment]
This is [very likely] the fault of BiomeTweaker - it happens from their call, causing a class load chain that just happens to involve my classes. Please send the error log to its author, there is nothing I can do to fix this.

**Comment by myrmex1** [comment]
Thank you. I will send it their way.

**Comment by superckl** [comment]
It's only partially my fault :P

You are actually loading the model classes on the server, but never do anything with them.

https://github.com/Ivorforce/YeGamolChattels/blob/master/src/main/java/ivorius/yegamolchattels/blocks/EnumPedestalEntry.java#L13

Please see the issue referenced above for my explanation of why this causes BiomeTweaker to throw an exception.
